# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: game-night-development

test:
  adapter: postgresql
  database: game-night-test

production:
  adapter: postgresql
  encoding: unicode
  # pool: 5
  # host: localhost
  database: game-night-production
  username: gamenight
  password: <%= ENV["DATABASE_PASSWORD"] %>
