# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: game-night-development

test:
  adapter: postgresql
  database: game-night-test

production:
  adapter: postgresql
  database: game-night-production
