# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: game-night-development

test:
  adapter: postgresql
  database: game-night-test

production:
  pool: 5
  adapter: postgresql
  encoding: unicode
  database: game_night_production
  # host: localhost
